### ISSUE TITLE
"Turn on Bluetooth to allow app to connect to accessories" IOS alert message

### ISSUE THREAD

**Issue by AlecMRogers** [don/cordova-plugin-ble-central#578] opened 2018-05-26 02:29 UTC
The alert mentioned in the title can be turned off with the following change to line 42 of BLECentralPlugin.m:

    manager = [[CBCentralManager alloc] initWithDelegate:self queue:nil options:@{CBCentralManagerOptionShowPowerAlertKey: @NO}];

**Comment by don** [comment] 2018-05-29 14:46
The code is working as designed. An enhancement would be to make dialog configurable by passing options to connect.

**Comment by don** [comment] 2018-05-29 15:26
Duplicate of #174

**Closed by don** 2018-05-29 15:26 UTC
