### ISSUE TITLE
Disconnect bug

### ISSUE THREAD

**Issue by ccravens** [don/cordova-plugin-ble-central#422] opened 2017-07-02 01:42 UTC
When invoking ble.disconnect() on Motorola Moto E (2nd Gen) Android 5.1 Lollipop, we get an error with the following message:

> Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.close()' on a null object reference

**Comment by don** [comment] 2017-07-07 13:03
Duplicate of #412

**Closed by don** 2017-07-07 13:03 UTC

**Comment by ccravens** [comment] 2017-07-12 23:37
@don I have opened a new bug due to the duplicate reference being for Android and the bug I am experiencing is for iOS: #428
