### ISSUE TITLE
Example Using Runtime Permissions for Android 6 

### ISSUE THREAD

**Issue by krumiaa** [don/cordova-plugin-ble-central#217] opened 2016-04-14 16:54 UTC
I have used this plugin successfully in the past but starting with Android 6 SDK 23 runtime permissions are required for it to work ( I get an error from console that android.permission.ACCESS_COARSE_LOCATION is required when I try to run the battery example and simply adding the permission to the manifest file doesn't work). An example in the documentation of how to use runtime permissions with this plugin would be much appreciated.

**Comment by don** [comment] 2016-04-15 00:18
Duplicate of #182

**Closed by don** 2016-04-15 00:18 UTC
