### ISSUE TITLE
Plugin not working on Galaxy S6 with Android 6.0.1, using cordova 6.1.0 and android platform 5.1.1 despite the edit in config.xml

### ISSUE THREAD

**Issue by Nico924** [don/cordova-plugin-ble-central#211] opened 2016-04-06 10:31 UTC
I saw the previous issues related to this subject however, the addition of 

<preference name="android-targetSdkVersion" value="22"/>  

in my config.xml did not change anything. I have no error but when I use the scan or startScan function, I am not able to discover any device (however if I go in the bluetooth section of my phone, I can see the device I am trying to connect to)

Does someone have any suggestion to help me ?

**Comment by don** [comment] 2016-04-06 15:43
If you're not seeing errors when starting the scan, the changes to config.xml likely worked.

When the plugin scans it finds Bluetooth Low Energy devices, if you're seeing your device in the Android Bluetooth settings, the device might be Bluetooth Classic. 

Make sure your device is advertising a Bluetooth Low Energy service. Make sure you can discover your peripheral using [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en).

**Comment by don** [comment] 2016-04-15 00:18
Duplicate of #182

**Closed by don** 2016-04-15 00:18 UTC
