### ISSUE TITLE
Unable to scan ble devices

### ISSUE THREAD

**Issue by Aman18493** [don/cordova-plugin-ble-central#186] opened 2016-02-23 05:32 UTC
I am unable to scan other mobile devices from my android device.What can be the issue?

 ble.scan([], 50, app.onDiscoverDevice, app.onError);

 onDiscoverDevice: function(device) {

            console.log(JSON.stringify(device));
            console.log("Device Info");
            var listItem = document.createElement('li'),
                html = '<b>' + device.name + '</b><br/>' +
                    'RSSI: ' + device.rssi + '&nbsp;|&nbsp;' +
                    device.id;

            listItem.dataset.deviceId = device.id;  // TODO
            listItem.innerHTML = html;
            deviceList.appendChild(listItem);            
 }

I am scanning for devices and adding it to the list.The device i m trying to use is samsung galaxy s6

**Comment by don** [comment] 2016-02-25 03:53
At first glance the code looks OK.

Are there devices near you that are advertising Bluetooth Low Energy services? If not, you won't see anything. Use [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) to verify there are other BLE devices nearby.

If you don't have any Bluetooth LE peripherals, you can use [LightBlue](https://itunes.apple.com/us/app/lightblue-explorer-bluetooth/id557428110?mt=8) to create virtual peripherals on iOS devices or nRF Master Control Panel to create virtual peripherals on newer Android devices.

[bleno](https://github.com/sandeepmistry/bleno) can be used to create Bluetooth Low Energy peripherals with Node.js on OS X, Linux and Windows.

**Comment by don** [comment] 2016-02-25 03:54
Duplicate of #173

**Closed by don** 2016-02-25 03:54 UTC
