### ISSUE TITLE
BLE fails to reconnect after app is killed by removing from recent apps list

### ISSUE THREAD

**Issue by I-Connect** [don/cordova-plugin-ble-central#650] opened 2018-12-09 13:45 UTC
Hi,

I am building an app that communicates via BLE with an ESP32 (BLE server).

If the app is stopped normally I see the esp32 closing the connection and going back to "advertising" state and accepting new connections when the app is started again.

But when the user kills the app (by swiping it out of the recent app list) some processes seem to remain active keeping the BLE connection alive ( the esp does not return to "advertising" state) and when starting the app again BLE fails to connect.
If I then go into the android settings and force stop the app, the BLE connection is ended and the esp returns to "advertising" and starting the app again works fine.

Any idea how to overcome this?

**Comment by don** [comment] 2019-10-18 02:24
It sounds like the phone might still be connected to the device when your app exits. I think you need to have your app disconnect from the peripheral while the app is exiting. I had some similar issues using the [PhoneGap Developer App](http://docs.phonegap.com/references/developer-app/). I created some hooks to handle this https://github.com/don/ITP-BluetoothLE/blob/master/phonegap/connect/www/js/disconnector.js

Duplicate of #126

**Closed by don** 2019-10-18 02:24 UTC
