### ISSUE TITLE
How to read Serial port data of Arduino Bluno?

### ISSUE THREAD

**Issue by stoneWeb** [don/cordova-plugin-ble-central#912] opened 2022-04-15 13:11 UTC
I can successfully write data and read it from the Arduino.  But this plug-in cannot read serial port data written from the Arduino.
But I use LightBlue to get data both ways.
```
ble.startNotification(deviceId, "DFB0", "DFB1", reciveData, err => {
      alert(JSON.stringify(err, null, 4));
    });
ble.writeWithoutResponse(deviceId, "DFB0", "DFB1", buffer, function () {
        }, function (err) {
        });
```

**Comment by peitschie** [comment] 2022-04-19 00:24
Hi @stoneWeb 

On the surface, what you're doing looks ok there. Only thing is are you waiting for the notifications to finish subscribing before attempting to read the serial port data? What happens if you put a 1s delay there between `startNotification` and the `writeWithoutReponse` call?

**Comment by stoneWeb** [comment] 2022-04-20 04:49
Adding a delay of 1s is the same, startNotification will not trigger reciveData.
if I call this:
```
ble.read(deviceId, "180A", "2A28", reciveData, err => {
      alert(JSON.stringify(err, null, 4));
    });
```
it always get {}.

**Comment by peitschie** [comment] 2022-04-20 05:02
What does your `receiveData` implementation look like? Is that an empty object there, or is it perhaps simply a non-printable type (e.g., many browsers show `{}` for an `ArrayBuffer`). 

E.g., 
![image](https://user-images.githubusercontent.com/1052079/164153993-a70bf3ab-3768-469b-addf-a36fc6c58a58.png)

**Comment by stoneWeb** [comment] 2022-04-20 07:03
Thank you so much! @peitschie 
Show {} is indeed the problem of this buffer, and I have confirmed that the data has been received.

But there are still two problems:
1. I don't know why `ble.startNotification` doesn't trigger reciveData, only I can read data by calling `ble.read` actively
2. Why can only read one byte of data per read?

This is arduino code, so I can only read "h".
```
if(Serial.available()) {
     Serial.write("hello world!");
     Serial.println();
   }
```
`ble.startNotification`  is in onConnect function.

**Comment by peitschie** [comment] 2022-04-20 11:32
Do you have any documentation regarding how the Arduino serial interface should be used via Bluetooth? I don't have a board locally, so can't really play myself to figure this out.

To double-check, what are you doing to decode the data from the notification and confirm it's only a single byte?
Also, is this iOS or Android?

**Comment by peitschie** [comment] 2022-04-20 11:33
Oh, I think [this comment](https://github.com/don/cordova-plugin-ble-central/issues/913#issuecomment-1103588937) in a recently identified quirk probably hints why calling `ble.read` on iOS causes the notification to trigger.

**Comment by stoneWeb** [comment] 2022-04-21 04:18
I tested my code and the notification was never triggered.
if I run:
```
onConnect() {
    ble.startNotification(deviceId, "DFB0", "DFB1", reciveData, err => {
      alert(JSON.stringify(err, null, 4));
    });
}
onClick() {
    ble.read(deviceId, "DFB0", "DFB1", readReciveData, err => {
      alert(JSON.stringify(err, null, 4));
    });
}
```
It's going to go into readReciveData function, but I can only get first one byte of send data.   and  startNotification never triggered.
```
readReciveData(buffer){
    conse.log(String.fromCharCode.apply(null, new Uint8Array(buffer)));
}
```

I ried [LightBlue](https://apps.apple.com/au/app/lightblue/id557428110) app and could receive the notification normally.

**Comment by peitschie** [comment] 2022-04-21 04:55
Does https://devdocs.io/dom/textdecoder give you any different results here?
E.g.,
```
console.log(new TextDecoder().decode(new Uint8Array(buffer)))
```

**Comment by stoneWeb** [comment] 2022-04-21 06:00
I don't think it's a problem of data parsing. Calling read in the LightBlue app also gets 1 byte, but the LightBlue app will trigger a notification, and the data obtained in the notification is correct. But my code doesn't trigger notification, never.

**Comment by peitschie** [comment] 2024-01-29 03:56
@stoneWeb I've encountered a similar issue here, and it was caused by an bug on the Arduino-based firmware side, where the `BLE2902` descriptor was not being added to the characteristic that should support `notify`.

To address the firmware issue and avoid the error, the following snippet was added to the firmware side:
```
pCharacteristic->addDescriptor(new BLE2902());
```

This is based of these examples from the Arduino library itself ([here](https://github.com/espressif/arduino-esp32/blob/cceebb58f170c34a2356f0d22106dd6f0d141023/libraries/BLE/examples/Notify/Notify.ino#L76)) and the [BLE C++ Guid.pdf](https://github.com/nkolban/esp32-snippets/blob/master/Documentation/BLE%20C%2B%2B%20Guide.pdf).

I'll close this out, but should the issue persist, feel free to re-open and we can keep digging.

**Closed by peitschie** 2024-01-29 03:56 UTC
Labels: question, ios

**Comment by peitschie** [comment] 2024-01-29 23:52
Same underlying issue occurring here as https://github.com/randdusing/cordova-plugin-bluetoothle/issues/405
