### ISSUE TITLE
Errors calling ble.disconnect() with Android

### ISSUE THREAD

**Issue by acutetech** [don/cordova-plugin-ble-central#416] opened 2017-06-13 08:32 UTC
When calling ble.disconnect() I see 3 cases:

1   Sometimes it works as expected: the success() callback is called and the peripheral sees the BLE connection dropped.

2   Sometime the failure() callback is called with this error message "Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.close()' on a null object reference". The peripheral does not see the BLE connection close (it eventually times out and closes the BLE connection itself). I am sure that I am passing a valid device_id (address) as I print it immediately before making the call. 

3  Sometimes the success() callback is called but the peripheral does not see the BLE connection close (it eventually times out and closes the BLE connection itself).

I cannot see a pattern. I don't know whether the two fault conditions are related or not . I am using a Samsung S4 with Android 5.0.1. I see a reference to close/disconnect in issue #154. Should there be a delay between gatt.disconnect() and gatt.close()? e.g. wait till disconnected before calling close()? Is this relevant? https://stackoverflow.com/questions/35986549/totally-disconnect-a-bluetooth-low-energy-device

**Comment by don** [comment] 2017-06-14 16:09
Duplicate of #412

**Closed by don** 2017-06-14 16:09 UTC
